[workspace]
members = [
  "constraint-macros",
  "trace-defs",
  "tracer",
]
exclude = ["miden-vm"]

resolver = "2"

# faster tests
[profile.test]
opt-level = 2
# faster tests
[profile.test.package.rand_chacha]
opt-level = 3

[profile.bench]
debug = true

[patch.crates-io]
winter-prover = { path = "../winterfell/prover" }
winter-math = { path = "../winterfell/math" }
winter-crypto = { path = "../winterfell/crypto" }
winter-air = { path = "../winterfell/air" }
winter-utils = { path = "../winterfell/utils/core" }
winter-rand-utils = { path = "../winterfell/utils/rand" }
winter-fri = { path = "../winterfell/fri" }
winter-verifier = { path = "../winterfell/verifier" }