[workspace]
members = [
  "constraint-macros",
  "trace-defs",
  "tracer",
]
exclude = ["miden-vm"]

resolver = "2"

# faster tests
[profile.test]
opt-level = 2
# faster tests
[profile.test.package.rand_chacha]
opt-level = 3

[profile.bench]
debug = true

[patch.crates-io]
winter-math = { git = "https://github.com/zeegomo/winterfell", branch = "add-link-proof" }
winter-prover = { git = "https://github.com/zeegomo/winterfell", branch = "add-link-proof" }
winter-utils = { git = "https://github.com/zeegomo/winterfell", branch = "add-link-proof" }
winter-crypto = { git = "https://github.com/zeegomo/winterfell", branch = "add-link-proof" }
winter-air = { git = "https://github.com/zeegomo/winterfell", branch = "add-link-proof" }
winter-verifier = { git = "https://github.com/zeegomo/winterfell", branch = "add-link-proof" }
winterfell = { git = "https://github.com/zeegomo/winterfell", branch = "add-link-proof" }