[package]
name = "rv-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rvsim = { version = "0.2", features = ["rv32c"] }
elf = "0.7"
clap = { version = "4", features = ["derive"] }
paste = "1.0.14"
seq-macro = "0.3.5"
winterfell = "0.7"
log = "0.4.20"
env_logger = "0.10.1"
winter-rand-utils = { path = "../../winterfell/utils/rand" }
winter-utils = { path = "../../winterfell/utils/core" }
rand = "0.8.5"
trace-defs = { path = "../trace-defs" }
constraint-macros = { path = "../constraint-macros" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.4"
paste = "1"

# faster tests
[profile.test.package.proptest]
opt-level = 3
# faster tests
[profile.test.package.rand_chacha]
opt-level = 3