[package]
name = "rv-tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rvsim = { version = "0.2", default-features = false }
elf = "0.7"
clap = { version = "4", features = ["derive"] }
paste = "1.0.14"
seq-macro = "0.3.5"
winterfell = "0.6"
log = "0.4.20"
env_logger = "0.10.1"
rand = "0.8.5"
trace-defs = { path = "../trace-defs" }
constraint-macros = { path = "../constraint-macros" }
miden-processor = { path = "../miden-vm/processor" }
miden-air = { path = "../miden-vm/air" }

[dev-dependencies]
paste = "1"
criterion = "0.3"
quickcheck = "1"
quickcheck_macros = "1"
once_cell = "1"
peak_alloc = "0.2.0"
serde_json = "1"
serde = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }

[[bench]]
name = "examples"
harness = false

[[bench]]
name = "mem"
harness = false

# https://bheisler.github.io/criterion.rs/book/faq.html#cargo-bench-gives-unrecognized-option-errors-for-valid-command-line-options
[lib]
bench = false

[[bin]]
name = "rv-tracer"
path = "src/main.rs"
bench = false

[features]
integration-test = []