name: Bench

on: [pull_request]

jobs:
  bench:
    name: run benchmark
    runs-on: [self-hosted, bench]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "tracer"
          branchName: ${{ github.base_ref }}
