name: Cpu Bench

on: [workflow_call]

jobs:
  bench-cpu:
    name: cpu benchmark
    runs-on: [alpha]
    steps:
      - uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "tracer"
          branchName: ${{ github.base_ref }}
          benchName: "examples"