name: Cpu Bench

on: [workflow_call]

jobs:
  bench-cpu:
    name: cpu benchmark
    runs-on: [alpha]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: boa-dev/criterion-compare-action@v3
        with:
          cwd: "tracer"
          branchName: ${{ github.base_ref }}
          benchName: "examples"