name: Memory Bench

on: [workflow_call]

jobs:
  bench-reference-mem:
    name: Benchmark fibonacci 1000 reference
    runs-on: [alpha]
    outputs:
      prove: ${{ steps.run_prove.out }}
      verify: ${{ steps.run_verify.out }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run bench exec
        id: run_exec
        run: cargo bench --bench fib_exec >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-exec
          path: tracer/dhat-heap.json
      - name: Run bench prove
        id: run_prove
        run: cargo bench --bench fib_prove >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-prove
          path: tracer/dhat-heap.json
      - name: Run bench verify
        id: run_verify
        run: cargo bench --bench fib_verify >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-verify
          path: tracer/dhat-heap.json

  bench-segmented-mem:
    name: Benchmark fibonacci 1000 segmented
    runs-on: [alpha]
    outputs: 
      peak_2048_prove: ${{ steps.prove.peak_2048 }}
      peak_2048_verify: ${{ steps.verify.peak_2048 }}
      out: "out"
    strategy:
      matrix:
        segment_len: [2048]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run bench prove segmented
        id: prove
        run: cargo bench --bench fib_prove_segmented -- --segment-len ${{ matrix.segment_len }}  >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-prove-segmented-${{ matrix.segment_len }}
          path: tracer/dhat-heap.json
      - name: Run bench verify segmented
        id: verify
        run: cargo bench --bench fib_verify_segmented -- --segment-len ${{ matrix.segment_len }} >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-verify-segmented-${{ matrix.segment_len }}
          path: tracer/dhat-heap.json

  write_report:
    runs-on: [alpha]
    name: Write report
    needs: [bench-segmented-mem, bench-reference-mem]
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            let prove = JSON.stringify(${{ needs.bench-segmented-mem.outputs }});
            let verify = JSON.stringify(${{ needs.bench-segmented-mem.outputs }});
            let prov = ${{ needs.bench-segmented-mem.outputs.out }}
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "**Fib 1000 peak memory usage segmented (4K)**:\n * prove: " + prove + " kB\n * verify: " + verify + " kB"
            })
      - uses: actions/github-script@v6
        with:
          script: |
            let prove =  ${{ needs.bench-reference-mem.outputs.prove }}[3] / 1024;
            let verify = ${{ needs.bench-reference-mem.outputs.verify }}[3] / 1024;
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "**Fib 1000 peak memory usage**:\n * exec:  kB\n * prove: " + prove + " kB\n * verify: " + verify + " kB"
            })
