name: Memory Bench

on: [workflow_call]

jobs:
  bench-reference-mem:
    name: Benchmark fibonacci 1000 reference
    runs-on: [alpha]
    outputs:
      prove: ${{ steps.run_prove.out }}
      verify: ${{ steps.run_verify.out }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - name: Run bench exec
        id: run_exec
        run: cargo bench --bench fib_exec >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-exec
          path: tracer/dhat-heap.json
      - name: Run bench prove
        id: run_prove
        run: cargo bench --bench fib_prove >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-prove
          path: tracer/dhat-heap.json
      - name: Run bench verify
        id: run_verify
        run: cargo bench --bench fib_verify >> $GITHUB_OUTPUT
      - uses: actions/upload-artifact@v4
        with:
          name: fib-verify
          path: tracer/dhat-heap.json
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "**Fib 1000 peak memory usage**:\n * exec: " + ${{ steps.run_exec.outputs.out }}[3] / 1024 + " kB\n * prove: " + ${{ steps.run_prove.outputs.out }}[3] / 1024 + " kB\n * verify: " + ${{ steps.run_verify.outputs.out }}[3] / 1024 + " kB"
            })

  bench_segmented_mem:
    name: Benchmark fibonacci 1000 segmented
    runs-on: [alpha]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/setup-python@v5
      - name: Run benches
        id: benches
        run: python tracer/benches/run_bench.py  >> $GITHUB_OUTPUT
      - uses: actions/github-script@v6
        with:
          script: |
            let seg_lens = ${{ steps.benches.outputs.segments }};
            let prove = ${{ steps.benches.outputs.prove }};
            let verify = ${{ steps.benches.outputs.verify }};
            let size = ${{ steps.benches.outputs.size }};
            let header = "|       |" + seg_lens.join(" | ");
            let separator = "|--|" + "--|".repeat(seg_lens.length);
            let p = "| prove peak mem (MB)   |";
            let v = "| verify peak mem (KB)  |";
            let s = "| proof total size (KB) |";

            for (let i = 0; i < seg_lens.length; i++) {
                p += `   ${prove[i].toFixed(2)} |`;
                v += `   ${verify[i].toFixed(2)} |`;
                s += `   ${size[i].toFixed(2)} |`;
            }

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "**Fib 1000 segmented**:\n " + header + "\n" + separator + "\n" + p + "\n" + v + "\n" + s + "\n"
            })
