name: Memory Bench

on: [pull_request]

jobs:
  bench-mem:
    name: fib exec mem
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: dtolnay/rust-toolchain@stable
      - name: Run bench
        id: run
        run: cargo bench --bench fib_exec >> $GITHUB_OUTPUT
      - name: List
        run: ls -ahl tracer/
      - uses: actions/upload-artifact@v4
        with:
          name: fib-verify
          path: tracer/dhat-heap.json
      - uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Max mem: " + ${{ steps.run.outputs.out }}[2] + " bytes"
            })