name: Rust

on: [workflow_call]

env:
  CARGO_TERM_COLOR: always
  QUICKCHECK_TESTS: 1000

jobs:
  clippy:
    runs-on: [alpha]
    - name: Run clippy
      run: cargo clippy -- -Dwarnings
  build-and-test:
    runs-on: [alpha]
    steps:
    - name: Build
      run: cargo build --verbose --manifest-path tracer/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path tracer/Cargo.toml --all-features
  