name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always
  QUICKCHECK_TESTS: 1000

jobs:
  build-and-test:
    runs-on: [alpha]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --verbose --manifest-path tracer/Cargo.toml
    - name: Run tests
      run: cargo test --verbose --manifest-path tracer/Cargo.toml --all-features
  clippy:
    runs-on: [alpha]
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: true
    - uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy
    - name: Build
      run: cargo clippy -- -Dwarnings